"""BDD exporter: generate Gherkin feature files from archledger records.

Only records with valid ``bdd`` metadata can be exported.  The output is
deterministic for a given record and includes a generated-header comment
so that users understand the file is derived, not canonical.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from archledger.bdd.models import BddExample
from archledger.repository import ArchitectureRepository


@dataclass(frozen=True, slots=True)
class BddExportResponse:
    """Response from ``export_bdd_record``."""

    schema: str = "archledger.bdd-export.v1"
    record_id: str = ""
    output_file: str = ""
    warnings: tuple[str, ...] = ()


def export_bdd_record(
    repo: ArchitectureRepository,
    record_id: str,
    out: str,
) -> BddExportResponse:
    """Export a record with ``bdd`` metadata as a Gherkin feature file.

    *record_id* is the archledger record id (e.g. ``al_runtime_0042``).
    *out* is the output file path (relative to workspace root or absolute).
    """
    from archledger.bdd.normalize import normalize_bdd_metadata
    from archledger.model import ArchitectureRecord

    record: ArchitectureRecord = repo.get_record(record_id)

    raw_bdd = record.metadata.get("bdd")
    if raw_bdd is None:
        raise ValueError(f"Record {record_id} has no bdd metadata; cannot export.")

    example, warnings = normalize_bdd_metadata(record_id, raw_bdd)
    if example is None:
        raise ValueError(
            f"Record {record_id} has invalid bdd metadata: " + "; ".join(warnings)
        )

    output_path = Path(out)
    if not output_path.is_absolute():
        output_path = repo.paths.workspace_root / output_path

    output_path.parent.mkdir(parents=True, exist_ok=True)

    content = _render_feature(example, record_id)
    output_path.write_text(content, encoding="utf-8")

    return BddExportResponse(
        record_id=record_id,
        output_file=str(output_path.relative_to(repo.paths.workspace_root)),
        warnings=tuple(warnings),
    )


def _render_feature(example: BddExample, record_id: str) -> str:
    """Render a deterministic Gherkin feature file from a BddExample."""
    lines: list[str] = []

    # Generated header
    lines.append(f"# Generated from archledger record {record_id}.")
    lines.append(
        "# Do not edit this file as canonical source unless ownership is changed."
    )
    lines.append("")

    # Tags
    if example.tags:
        lines.append(" ".join(f"@{tag}" for tag in example.tags))

    # Feature
    lines.append(f"Feature: {example.feature}")
    lines.append("")

    # Rule (optional)
    if example.rule:
        lines.append(f"  Rule: {example.rule}")
        lines.append("")

    # Scenario
    indent = "    " if example.rule else "  "
    lines.append(f"{indent}Scenario: {example.scenario}")
    lines.append("")

    # Steps
    for step in example.given:
        lines.append(f"{indent}  Given {step}")
    for step in example.when:
        lines.append(f"{indent}  When {step}")
    for step in example.then:
        lines.append(f"{indent}  Then {step}")
    lines.append("")

    return "\n".join(lines)


__all__ = ["BddExportResponse", "export_bdd_record"]
